# Generated by Django 3.0.6 on 2020-05-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
